package mod.xtronius.rc_mod.lib;

import java.util.HashMap;

import net.minecraft.entity.EntityLiving;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.item.Item;

public class EntityInfo {
	
	public static HashMap<String, Boolean> isEntityLiving = new HashMap<String, Boolean>();
	public static HashMap<String, String> EntityName = new HashMap<String, String>();
	public static HashMap<String, Integer> EntityLvlMin = new HashMap<String, Integer>();
	public static HashMap<String, Integer> EntityLvlMax = new HashMap<String, Integer>();
	public static HashMap<String, Integer> EntityLvlMinChild = new HashMap<String, Integer>();
	public static HashMap<String, Integer> EntityLvlMaxChild = new HashMap<String, Integer>();
	public static HashMap<String, Float> EntityMobXp = new HashMap<String, Float>();
	public static HashMap<Integer, Integer> EntityLvl = new HashMap<Integer, Integer>();
	public static HashMap<String, Float> EntityMobHealth = new HashMap<String, Float>();
	
	public EntityInfo() {
		
		isEntityLiving.put("Mob", true);
		isEntityLiving.put("Monster", true);
		isEntityLiving.put("Creeper", true);
		isEntityLiving.put("Skeleton", true);
		isEntityLiving.put("Spider", true);
		isEntityLiving.put("Giant", true);
		isEntityLiving.put("Zombie", true);
		isEntityLiving.put("Slime", true);
		isEntityLiving.put("Ghast", true);
		isEntityLiving.put("PigZombie", true);
		isEntityLiving.put("Enderman", true);
		isEntityLiving.put("CaveSpider", true);
		isEntityLiving.put("Silverfish", true);
		isEntityLiving.put("Blaze", true);
		isEntityLiving.put("LavaSlime", true);
		isEntityLiving.put("EnderDragon", true);
		isEntityLiving.put("WitherBoss", true);
		isEntityLiving.put("Bat", true);
		isEntityLiving.put("Witch", true);
		isEntityLiving.put("Pig", true);
		isEntityLiving.put("Sheep", true);
		isEntityLiving.put("Cow", true);
		isEntityLiving.put("Chicken", true);
		isEntityLiving.put("Squid", true);
		isEntityLiving.put("Wolf", true);
		isEntityLiving.put("MushroomCow", true);
		isEntityLiving.put("SnowMan", true);
		isEntityLiving.put("Ozelot", true);
		isEntityLiving.put("VillagerGolem", true);
		isEntityLiving.put("EntityHorse", true);
		isEntityLiving.put("Chicken", true);
		
		EntityName.put("Mob", "Mob");
		EntityName.put("Monster", "Monster");
		EntityName.put("Creeper", "Creeper");
		EntityName.put("Skeleton", "Skeleton");
		EntityName.put("Spider", "Spider");
		EntityName.put("Giant", "Giant");
		EntityName.put("Zombie", "Zombie");
		EntityName.put("Slime", "Slime");
		EntityName.put("Ghast", "Ghast");
		EntityName.put("PigZombie", "PigZombie");
		EntityName.put("Enderman", "Tall Dude");
		EntityName.put("CaveSpider", "Cave Spider");
		EntityName.put("Silverfish", "Rat");
		EntityName.put("Blaze", "Fire Man");
		EntityName.put("LavaSlime", "Lava Slime");
		EntityName.put("EnderDragon", "Ender Dragon");
		EntityName.put("WitherBoss", "Wither Boss");
		EntityName.put("Bat", "Bat");
		EntityName.put("Witch", "Witch");
		EntityName.put("Pig", "Pig");
		EntityName.put("Sheep", "Ram");
		EntityName.put("Cow", "Cow");
		EntityName.put("Chicken", "Chicken");
		EntityName.put("Squid", "Squid");
		EntityName.put("Wolf", "Stray Dog");
		EntityName.put("MushroomCow", "Fungus Covered Cow");
		EntityName.put("SnowMan", "Jack Frost");
		EntityName.put("Ozelot", "Cat");
		EntityName.put("VillagerGolem", "Iron Golem");
		EntityName.put("EntityHorse", "Unicorn with No Horn");
		EntityName.put("Chicken", "Chicken");
		
		EntityMobXp.put("Mob", 1F);
		EntityMobXp.put("Monster", 1F);
		EntityMobXp.put("Creeper", 1F);
		EntityMobXp.put("Skeleton", 1F);
		EntityMobXp.put("Spider", 1F);
		EntityMobXp.put("Giant", 1F);
		EntityMobXp.put("Zombie", 1F);
		EntityMobXp.put("Slime", 1F);
		EntityMobXp.put("Ghast", 1F);
		EntityMobXp.put("PigZombie", 1F);
		EntityMobXp.put("Enderman", 1F);
		EntityMobXp.put("CaveSpider", 1F);
		EntityMobXp.put("Silverfish", 1F);
		EntityMobXp.put("Blaze", 1F);
		EntityMobXp.put("LavaSlime", 1F);
		EntityMobXp.put("EnderDragon", 1F);
		EntityMobXp.put("WitherBoss", 1F);
		EntityMobXp.put("Bat", 1F);
		EntityMobXp.put("Witch", 1F);
		EntityMobXp.put("Pig", 1F);
		EntityMobXp.put("Sheep", 1F);
		EntityMobXp.put("Cow", 26.5F);
		EntityMobXp.put("Chicken", 1F);
		EntityMobXp.put("Squid", 1F);
		EntityMobXp.put("Wolf", 1F);
		EntityMobXp.put("MushroomCow", 1F);
		EntityMobXp.put("SnowMan", 1F);
		EntityMobXp.put("Ozelot", 1F);
		EntityMobXp.put("VillagerGolem", 1F);
		EntityMobXp.put("EntityHorse", 1F);
		EntityMobXp.put("Chicken", 24.9F);
		
		EntityMobHealth.put("Mob", 1F);
		EntityMobHealth.put("Monster", 1F);
		EntityMobHealth.put("Creeper", 1F);
		EntityMobHealth.put("Skeleton", 1F);
		EntityMobHealth.put("Spider", 1F);
		EntityMobHealth.put("Giant", 1F);
		EntityMobHealth.put("Zombie", 1F);
		EntityMobHealth.put("Slime", 1F);
		EntityMobHealth.put("Ghast", 1F);
		EntityMobHealth.put("PigZombie", 1F);
		EntityMobHealth.put("Enderman", 1F);
		EntityMobHealth.put("CaveSpider", 1F);
		EntityMobHealth.put("Silverfish", 1F);
		EntityMobHealth.put("Blaze", 1F);
		EntityMobHealth.put("LavaSlime", 1F);
		EntityMobHealth.put("EnderDragon", 1F);
		EntityMobHealth.put("WitherBoss", 1F);
		EntityMobHealth.put("Bat", 1F);
		EntityMobHealth.put("Witch", 1F);
		EntityMobHealth.put("Pig", 1F);
		EntityMobHealth.put("Sheep", 1F);
		EntityMobHealth.put("Cow", 150F);
		EntityMobHealth.put("Chicken", 50F);
		EntityMobHealth.put("Squid", 1F);
		EntityMobHealth.put("Wolf", 1F);
		EntityMobHealth.put("MushroomCow", 1F);
		EntityMobHealth.put("SnowMan", 1F);
		EntityMobHealth.put("Ozelot", 1F);
		EntityMobHealth.put("VillagerGolem", 1F);
		EntityMobHealth.put("EntityHorse", 1F);
		EntityMobHealth.put("Chicken", 1F);
		
		EntityLvl.put(0, 0);
		EntityLvl.put(1, 1);
		EntityLvl.put(2, 1);
		EntityLvl.put(3, 1);
		EntityLvl.put(4, 1);
		EntityLvl.put(5, 1);
		EntityLvl.put(6, 1);
		EntityLvl.put(7, 1);
		EntityLvl.put(8, 1);
		EntityLvl.put(9, 1);
		EntityLvl.put(10, 1);
		EntityLvl.put(11, 1);
		EntityLvl.put(12, 1);
		EntityLvl.put(14, 1);
		EntityLvl.put(15, 1);
		EntityLvl.put(16, 1);
		EntityLvl.put(17, 1);
		EntityLvl.put(18, 1);
		EntityLvl.put(19, 1);
		EntityLvl.put(20, 1);
		EntityLvl.put(21, 1);
		EntityLvl.put(22, 1);
		EntityLvl.put(23, 1);
		EntityLvl.put(24, 1);
		EntityLvl.put(25, 1);
		EntityLvl.put(26, 1);
		EntityLvl.put(27, 1);
		EntityLvl.put(28, 1);
		EntityLvl.put(29, 1);
		EntityLvl.put(31, 1);
		EntityLvl.put(32, 1);
		
		EntityLvlMin.put("Mob", 1);
		EntityLvlMin.put("Monster", 1);
		EntityLvlMin.put("Creeper", 1);
		EntityLvlMin.put("Skeleton", 1);
		EntityLvlMin.put("Spider", 1);
		EntityLvlMin.put("Giant", 1);
		EntityLvlMin.put("Zombie", 1);
		EntityLvlMin.put("Slime", 1);
		EntityLvlMin.put("Ghast", 1);
		EntityLvlMin.put("PigZombie", 1);
		EntityLvlMin.put("Enderman", 1);
		EntityLvlMin.put("CaveSpider", 1);
		EntityLvlMin.put("Silverfish", 1);
		EntityLvlMin.put("Blaze", 1);
		EntityLvlMin.put("LavaSlime", 1);
		EntityLvlMin.put("EnderDragon", 1);
		EntityLvlMin.put("WitherBoss", 1);
		EntityLvlMin.put("Bat", 1);
		EntityLvlMin.put("Witch", 1);
		EntityLvlMin.put("Pig", 1);
		EntityLvlMin.put("Sheep", 1);
		EntityLvlMin.put("Cow", 1);
		EntityLvlMin.put("Chicken", 1);
		EntityLvlMin.put("Squid", 1);
		EntityLvlMin.put("Wolf", 1);
		EntityLvlMin.put("MushroomCow", 1);
		EntityLvlMin.put("SnowMan", 1);
		EntityLvlMin.put("Ozelot", 1);
		EntityLvlMin.put("VillagerGolem", 1);
		EntityLvlMin.put("EntityHorse", 1);
		EntityLvlMin.put("Chicken", 1);
		
		EntityLvlMax.put("Mob", 15);
		EntityLvlMax.put("Monster", 15);
		EntityLvlMax.put("Creeper", 15);
		EntityLvlMax.put("Skeleton", 15);
		EntityLvlMax.put("Spider", 15);
		EntityLvlMax.put("Giant", 15);
		EntityLvlMax.put("Zombie", 15);
		EntityLvlMax.put("Slime", 15);
		EntityLvlMax.put("Ghast", 15);
		EntityLvlMax.put("PigZombie", 15);
		EntityLvlMax.put("Enderman", 15);
		EntityLvlMax.put("CaveSpider", 15);
		EntityLvlMax.put("Silverfish", 15);
		EntityLvlMax.put("Blaze", 15);
		EntityLvlMax.put("LavaSlime", 15);
		EntityLvlMax.put("EnderDragon", 15);
		EntityLvlMax.put("WitherBoss", 15);
		EntityLvlMax.put("Bat", 15);
		EntityLvlMax.put("Witch", 15);
		EntityLvlMax.put("Pig", 15);
		EntityLvlMax.put("Sheep", 15);
		EntityLvlMax.put("Cow", 15);
		EntityLvlMax.put("Chicken", 15);
		EntityLvlMax.put("Squid", 15);
		EntityLvlMax.put("Wolf", 15);
		EntityLvlMax.put("MushroomCow", 15);
		EntityLvlMax.put("SnowMan", 15);
		EntityLvlMax.put("Ozelot", 15);
		EntityLvlMax.put("VillagerGolem", 15);
		EntityLvlMax.put("EntityHorse", 15);
		EntityLvlMax.put("Chicken", 15);
		
		EntityLvlMinChild.put("Mob", 1);
		EntityLvlMinChild.put("Monster", 1);
		EntityLvlMinChild.put("Creeper", 1);
		EntityLvlMinChild.put("Skeleton", 1);
		EntityLvlMinChild.put("Spider", 1);
		EntityLvlMinChild.put("Giant", 1);
		EntityLvlMinChild.put("Zombie", 1);
		EntityLvlMinChild.put("Slime", 1);
		EntityLvlMinChild.put("Ghast", 1);
		EntityLvlMinChild.put("PigZombie", 1);
		EntityLvlMinChild.put("Enderman", 1);
		EntityLvlMinChild.put("CaveSpider", 1);
		EntityLvlMinChild.put("Silverfish", 1);
		EntityLvlMinChild.put("Blaze", 1);
		EntityLvlMinChild.put("LavaSlime", 1);
		EntityLvlMinChild.put("EnderDragon", 1);
		EntityLvlMinChild.put("WitherBoss", 1);
		EntityLvlMinChild.put("Bat", 1);
		EntityLvlMinChild.put("Witch", 1);
		EntityLvlMinChild.put("Pig", 1);
		EntityLvlMinChild.put("Sheep", 1);
		EntityLvlMinChild.put("Cow", 1);
		EntityLvlMinChild.put("Chicken", 1);
		EntityLvlMinChild.put("Squid", 1);
		EntityLvlMinChild.put("Wolf", 1);
		EntityLvlMinChild.put("MushroomCow", 1);
		EntityLvlMinChild.put("SnowMan", 1);
		EntityLvlMinChild.put("Ozelot", 1);
		EntityLvlMinChild.put("VillagerGolem", 1);
		EntityLvlMinChild.put("EntityHorse", 1);
		EntityLvlMinChild.put("Chicken", 1);
		
		EntityLvlMaxChild.put("Mob", 7);
		EntityLvlMaxChild.put("Monster", 7);
		EntityLvlMaxChild.put("Creeper", 7);
		EntityLvlMaxChild.put("Skeleton", 7);
		EntityLvlMaxChild.put("Spider", 7);
		EntityLvlMaxChild.put("Giant", 7);
		EntityLvlMaxChild.put("Zombie", 7);
		EntityLvlMaxChild.put("Slime", 7);
		EntityLvlMaxChild.put("Ghast", 7);
		EntityLvlMaxChild.put("PigZombie", 7);
		EntityLvlMaxChild.put("Enderman", 7);
		EntityLvlMaxChild.put("CaveSpider", 7);
		EntityLvlMaxChild.put("Silverfish", 7);
		EntityLvlMaxChild.put("Blaze", 7);
		EntityLvlMaxChild.put("LavaSlime", 7);
		EntityLvlMaxChild.put("EnderDragon", 7);
		EntityLvlMaxChild.put("WitherBoss", 7);
		EntityLvlMaxChild.put("Bat", 7);
		EntityLvlMaxChild.put("Witch", 7);
		EntityLvlMaxChild.put("Pig", 7);
		EntityLvlMaxChild.put("Sheep", 7);
		EntityLvlMaxChild.put("Cow", 7);
		EntityLvlMaxChild.put("Chicken", 7);
		EntityLvlMaxChild.put("Squid", 7);
		EntityLvlMaxChild.put("Wolf", 7);
		EntityLvlMaxChild.put("MushroomCow", 7);
		EntityLvlMaxChild.put("SnowMan", 7);
		EntityLvlMaxChild.put("Ozelot", 7);
		EntityLvlMaxChild.put("VillagerGolem", 7);
		EntityLvlMaxChild.put("EntityHorse", 7);
		EntityLvlMaxChild.put("Chicken", 7);
	}
	
	public boolean getIsEntityLiving(String entity) {
		if(isEntityLiving.get(entity) == null) {
			return false;
		}
		return isEntityLiving.get(entity);
	}
}
